using FluentAssertions;
using Lms.Auth.Application.DTOs;
using Lms.Auth.Application.Interfaces;
using Lms.Auth.Application.Services;
using Lms.Auth.Domain.Entities;
using Lms.Auth.Domain.Interfaces;
using Moq;

namespace Lms.Auth.UnitTests.Application.Services;

/// <summary>
/// Unit tests for AuthService business logic.
/// 
/// UPDATED FLOW:
/// - Auth Service triggers Verification service (no code generation)
/// - Verification generates + stores code; EmailEvent delivers it
/// - Auth Service calls Verification service to validate code
/// </summary>
public class AuthServiceTests
{
    private readonly Mock<IUserRepository> _userRepositoryMock;
    private readonly Mock<IRefreshTokenRepository> _refreshTokenRepositoryMock;
    private readonly Mock<IPasswordHasher> _passwordHasherMock;
    private readonly Mock<IJwtTokenGenerator> _jwtTokenGeneratorMock;
    private readonly Mock<IApplicationDbContext> _contextMock;
    private readonly Mock<IVerificationClient> _verificationClientMock;

    private readonly AuthService _authService;

    public AuthServiceTests()
    {
        _userRepositoryMock = new Mock<IUserRepository>();
        _refreshTokenRepositoryMock = new Mock<IRefreshTokenRepository>();
        _passwordHasherMock = new Mock<IPasswordHasher>();
        _jwtTokenGeneratorMock = new Mock<IJwtTokenGenerator>();
        _contextMock = new Mock<IApplicationDbContext>();
        _verificationClientMock = new Mock<IVerificationClient>();

        _jwtTokenGeneratorMock.Setup(j => j.AccessTokenExpirationMinutes).Returns(15);
        _jwtTokenGeneratorMock.Setup(j => j.RefreshTokenExpirationDays).Returns(7);

        _authService = new AuthService(
            _userRepositoryMock.Object,
            _refreshTokenRepositoryMock.Object,
            _passwordHasherMock.Object,
            _jwtTokenGeneratorMock.Object,
            _contextMock.Object,
            _verificationClientMock.Object);
    }

    // ================================================================
    // REGISTRATION TESTS
    // ================================================================

    /// <summary>
    /// TEST: Registration sends ONLY email to Service Bus.
    /// No code is generated by Auth Service.
    /// User must verify email before receiving tokens.
    /// </summary>
    [Fact]
    public async Task RegisterAsync_WithValidData_ShouldTriggerVerification()
    {
        // ARRANGE
        var request = new RegisterRequest
        {
            Email = "newuser@lms.com",
            Password = "StrongPass123!",
            FirstName = "Jane",
            LastName = "Smith"
        };

        _userRepositoryMock
            .Setup(r => r.EmailExistsAsync(request.Email))
            .ReturnsAsync(false);

        _passwordHasherMock
            .Setup(p => p.Hash(request.Password))
            .Returns("hashed_password_xyz");

        _contextMock
            .Setup(c => c.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        // ACT
        var result = await _authService.RegisterAsync(request);

        // ASSERT
        result.Should().NotBeNull("registration should succeed");
        result!.RequiresEmailVerification.Should().BeTrue("new users must verify email");
        result.AccessToken.Should().BeEmpty("tokens not issued until email verified");
        result.RefreshToken.Should().BeEmpty("tokens not issued until email verified");
        result.User.Email.Should().Be("newuser@lms.com");

        // Verify Service Bus was called with ONLY the email address
        _verificationClientMock.Verify(
            s => s.SendVerificationAsync("newuser@lms.com"),
            Times.Once,
            "verification email request must be published to Service Bus");

        // Verify user was added
        _userRepositoryMock.Verify(
            r => r.Add(It.IsAny<User>()),
            Times.Once,
            "new user should be added");
    }

    /// <summary>
    /// TEST: Duplicate email should return null and NOT publish to Service Bus.
    /// </summary>
    [Fact]
    public async Task RegisterAsync_WithDuplicateEmail_ShouldReturnNull()
    {
        var request = new RegisterRequest
        {
            Email = "existing@lms.com",
            Password = "StrongPass123!",
            FirstName = "Jane",
            LastName = "Smith"
        };

        _userRepositoryMock
            .Setup(r => r.EmailExistsAsync(request.Email))
            .ReturnsAsync(true);

        var result = await _authService.RegisterAsync(request);

        result.Should().BeNull("duplicate email should fail");

        // Service Bus should NOT be called
        _verificationClientMock.Verify(
            s => s.SendVerificationAsync(It.IsAny<string>()),
            Times.Never,
            "no verification email for duplicate registration");
    }

    // ================================================================
    // LOGIN TESTS
    // ================================================================

    /// <summary>
    /// TEST: Unverified user should NOT receive tokens on login.
    /// </summary>
    [Fact]
    public async Task LoginAsync_WithUnverifiedEmail_ShouldRequireVerification()
    {
        var request = new LoginRequest
        {
            Email = "unverified@lms.com",
            Password = "correct_password"
        };

        var unverifiedUser = new User(
            "unverified@lms.com",
            "hashed_password",
            "John",
            "Doe",
            "Student");
        // EmailConfirmed is false by default

        _userRepositoryMock
            .Setup(r => r.GetByEmailAsync(request.Email))
            .ReturnsAsync(unverifiedUser);

        _passwordHasherMock
            .Setup(p => p.Verify(request.Password, unverifiedUser.PasswordHash))
            .Returns(true);

        var result = await _authService.LoginAsync(request);

        result.Should().NotBeNull("user exists and password is correct");
        result!.RequiresEmailVerification.Should().BeTrue("email not verified yet");
        result.AccessToken.Should().BeEmpty("no token until verified");
    }

    /// <summary>
    /// TEST: Verified user with valid credentials should receive tokens.
    /// </summary>
    [Fact]
    public async Task LoginAsync_WithVerifiedEmail_ShouldReturnTokens()
    {
        var request = new LoginRequest
        {
            Email = "verified@lms.com",
            Password = "correct_password"
        };

        var verifiedUser = new User(
            "verified@lms.com",
            "hashed_password",
            "John",
            "Doe",
            "Student");
        verifiedUser.ConfirmEmail();

        _userRepositoryMock
            .Setup(r => r.GetByEmailAsync(request.Email))
            .ReturnsAsync(verifiedUser);

        _passwordHasherMock
            .Setup(p => p.Verify(request.Password, verifiedUser.PasswordHash))
            .Returns(true);

        _jwtTokenGeneratorMock
            .Setup(j => j.GenerateAccessToken(It.IsAny<User>()))
            .Returns("login_access_token");
        _jwtTokenGeneratorMock
            .Setup(j => j.GenerateRefreshToken())
            .Returns("login_refresh_token");

        _contextMock
            .Setup(c => c.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        var result = await _authService.LoginAsync(request);

        result.Should().NotBeNull("verified user should log in successfully");
        result!.AccessToken.Should().Be("login_access_token");
        result.RequiresEmailVerification.Should().BeFalse("email is verified");
        result.User.EmailConfirmed.Should().BeTrue();
    }

    [Fact]
    public async Task LoginAsync_WithWrongPassword_ShouldReturnNull()
    {
        var request = new LoginRequest { Email = "user@lms.com", Password = "wrong_password" };
        var existingUser = new User("user@lms.com", "hashed_password", "John", "Doe", "Student");
        existingUser.ConfirmEmail();

        _userRepositoryMock.Setup(r => r.GetByEmailAsync(request.Email)).ReturnsAsync(existingUser);
        _passwordHasherMock.Setup(p => p.Verify(request.Password, existingUser.PasswordHash)).Returns(false);

        var result = await _authService.LoginAsync(request);
        result.Should().BeNull("wrong password should fail");
    }

    [Fact]
    public async Task LoginAsync_WithInactiveUser_ShouldReturnNull()
    {
        var request = new LoginRequest { Email = "inactive@lms.com", Password = "password" };
        var inactiveUser = new User("inactive@lms.com", "hashed_password", "John", "Doe", "Student");
        inactiveUser.ConfirmEmail();
        typeof(User).GetProperty("IsActive")?.SetValue(inactiveUser, false);

        _userRepositoryMock.Setup(r => r.GetByEmailAsync(request.Email)).ReturnsAsync(inactiveUser);
        _passwordHasherMock.Setup(p => p.Verify(request.Password, inactiveUser.PasswordHash)).Returns(true);

        var result = await _authService.LoginAsync(request);
        result.Should().BeNull("inactive users cannot log in");
    }

    // ================================================================
    // EMAIL VERIFICATION TESTS (Uses Verification service)
    // ================================================================

    /// <summary>
    /// TEST: Verify email calls Verification service and confirms email on success.
    /// </summary>
    [Fact]
    public async Task VerifyEmailAsync_WithValidCode_ShouldReturnTrue()
    {
        // ARRANGE
        var user = new User("test@lms.com", "hash", "Test", "User", "Student");

        _userRepositoryMock
            .Setup(r => r.GetByEmailAsync("test@lms.com"))
            .ReturnsAsync(user);

        // Mock Email Service to return valid
        _verificationClientMock
            .Setup(e => e.ValidateCodeAsync("test@lms.com", "245789"))
            .ReturnsAsync(true);

        _contextMock
            .Setup(c => c.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        // ACT
        var result = await _authService.VerifyEmailAsync("test@lms.com", "245789");

        // ASSERT
        result.Should().BeTrue("correct code should verify email");
        user.EmailConfirmed.Should().BeTrue("user should be marked as verified");

        // Verify Email Service was called
        _verificationClientMock.Verify(
            e => e.ValidateCodeAsync("test@lms.com", "245789"),
            Times.Once,
            "Email Service should be called to verify code");
    }

    /// <summary>
    /// TEST: Verify email with invalid code should return false.
    /// </summary>
    [Fact]
    public async Task VerifyEmailAsync_WithInvalidCode_ShouldReturnFalse()
    {
        // ARRANGE
        var user = new User("test@lms.com", "hash", "Test", "User", "Student");

        _userRepositoryMock
            .Setup(r => r.GetByEmailAsync("test@lms.com"))
            .ReturnsAsync(user);

        _verificationClientMock
            .Setup(e => e.ValidateCodeAsync("test@lms.com", "000000"))
            .ReturnsAsync(false);

        // ACT
        var result = await _authService.VerifyEmailAsync("test@lms.com", "000000");

        // ASSERT
        result.Should().BeFalse("wrong code should fail");
        user.EmailConfirmed.Should().BeFalse("email should NOT be confirmed");
    }

    /// <summary>
    /// TEST: Already verified email should return true without calling Email Service.
    /// </summary>
    [Fact]
    public async Task VerifyEmailAsync_AlreadyVerified_ShouldReturnTrue()
    {
        // ARRANGE
        var user = new User("test@lms.com", "hash", "Test", "User", "Student");
        user.ConfirmEmail();

        _userRepositoryMock
            .Setup(r => r.GetByEmailAsync("test@lms.com"))
            .ReturnsAsync(user);

        // ACT
        var result = await _authService.VerifyEmailAsync("test@lms.com", "any-code");

        // ASSERT
        result.Should().BeTrue("already verified should return true");

        // Email Service should NOT be called
        _verificationClientMock.Verify(
            e => e.ValidateCodeAsync(It.IsAny<string>(), It.IsAny<string>()),
            Times.Never,
            "Email Service should not be called for already verified users");
    }

    /// <summary>
    /// TEST: Verify for non-existent user should return false.
    /// </summary>
    [Fact]
    public async Task VerifyEmailAsync_UserNotFound_ShouldReturnFalse()
    {
        _userRepositoryMock
            .Setup(r => r.GetByEmailAsync("unknown@lms.com"))
            .ReturnsAsync((User?)null);

        var result = await _authService.VerifyEmailAsync("unknown@lms.com", "123456");

        result.Should().BeFalse("non-existent user should fail");
    }

    // ================================================================
    // RESEND VERIFICATION TESTS (triggers Verification service)
    // ================================================================

    /// <summary>
    /// TEST: Resend verification triggers the Verification service.
    /// </summary>
    [Fact]
    public async Task ResendVerificationCodeAsync_ShouldTriggerVerification()
    {
        // ARRANGE
        var user = new User("test@lms.com", "hash", "Test", "User", "Student");

        _userRepositoryMock
            .Setup(r => r.GetByEmailAsync("test@lms.com"))
            .ReturnsAsync(user);

        _contextMock
            .Setup(c => c.SaveChangesAsync(It.IsAny<CancellationToken>()))
            .ReturnsAsync(1);

        // ACT
        var result = await _authService.ResendVerificationCodeAsync("test@lms.com");

        // ASSERT
        result.Should().BeTrue("resend should succeed");

        // Verify Service Bus was called with email
        _verificationClientMock.Verify(
            s => s.SendVerificationAsync("test@lms.com"),
            Times.Once,
            "verification email should be published to Service Bus");
    }

    /// <summary>
    /// TEST: Resend for already verified email should return false.
    /// </summary>
    [Fact]
    public async Task ResendVerificationCodeAsync_AlreadyVerified_ShouldReturnFalse()
    {
        var user = new User("test@lms.com", "hash", "Test", "User", "Student");
        user.ConfirmEmail();

        _userRepositoryMock
            .Setup(r => r.GetByEmailAsync("test@lms.com"))
            .ReturnsAsync(user);

        var result = await _authService.ResendVerificationCodeAsync("test@lms.com");

        result.Should().BeFalse("already verified should not resend");

        _verificationClientMock.Verify(
            s => s.SendVerificationAsync(It.IsAny<string>()),
            Times.Never,
            "no email for already verified users");
    }

    /// <summary>
    /// TEST: Resend for non-existent user should return false.
    /// </summary>
    [Fact]
    public async Task ResendVerificationCodeAsync_UserNotFound_ShouldReturnFalse()
    {
        _userRepositoryMock
            .Setup(r => r.GetByEmailAsync("unknown@lms.com"))
            .ReturnsAsync((User?)null);

        var result = await _authService.ResendVerificationCodeAsync("unknown@lms.com");

        result.Should().BeFalse("non-existent user should fail");
    }

    // ================================================================
    // REFRESH TOKEN TESTS
    // ================================================================

    [Fact]
    public async Task RefreshTokenAsync_WithValidToken_ShouldRotateTokens()
    {
        var oldRefreshTokenValue = "old_refresh_token";
        var user = new User("user@lms.com", "hashed_password", "John", "Doe", "Student");
        user.ConfirmEmail();

        var oldToken = new RefreshToken(oldRefreshTokenValue, DateTime.UtcNow.AddDays(1), user);

        _refreshTokenRepositoryMock.Setup(r => r.GetByTokenAsync(oldRefreshTokenValue)).ReturnsAsync(oldToken);
        _jwtTokenGeneratorMock.Setup(j => j.GenerateAccessToken(It.IsAny<User>())).Returns("new_access_token");
        _jwtTokenGeneratorMock.Setup(j => j.GenerateRefreshToken()).Returns("new_refresh_token");
        _contextMock.Setup(c => c.SaveChangesAsync(It.IsAny<CancellationToken>())).ReturnsAsync(1);

        var result = await _authService.RefreshTokenAsync(oldRefreshTokenValue);

        result.Should().NotBeNull();
        result!.AccessToken.Should().Be("new_access_token");
        result.RefreshToken.Should().Be("new_refresh_token");
        oldToken.IsRevoked.Should().BeTrue("old token should be revoked");
    }

    [Fact]
    public async Task RefreshTokenAsync_WithExpiredToken_ShouldReturnNull()
    {
        var user = new User("user@lms.com", "hash", "John", "Doe", "Student");
        var expiredToken = new RefreshToken("expired_token", DateTime.UtcNow.AddDays(-1), user);

        _refreshTokenRepositoryMock.Setup(r => r.GetByTokenAsync("expired_token")).ReturnsAsync(expiredToken);

        var result = await _authService.RefreshTokenAsync("expired_token");
        result.Should().BeNull("expired token should be rejected");
    }

    // ================================================================
    // VALIDATE TOKEN TEST
    // ================================================================

    [Fact]
    public async Task ValidateTokenAsync_WithActiveUser_ShouldReturnUserResponse()
    {
        var user = new User("user@lms.com", "hashed_password", "John", "Doe", "Instructor");
        user.ConfirmEmail();

        var userId = Guid.NewGuid();
        _userRepositoryMock.Setup(r => r.GetByIdAsync(userId)).ReturnsAsync(user);

        var result = await _authService.ValidateTokenAsync(userId);

        result.Should().NotBeNull();
        result!.Email.Should().Be("user@lms.com");
        result.Role.Should().Be("Instructor");
        result.IsActive.Should().BeTrue();
        result.EmailConfirmed.Should().BeTrue();
    }
}